# main section
title: ffmpeg-kit
baseurl: "/ffmpeg-kit"
locale: "en"
theme: jekyll-theme-minimal
markdown: kramdown

# github section
show_downloads: true
github:
  zip_url:
  tar_url: 
  owner_name: ARTHENICA
  owner_url: https://github.com/arthenica