name: tvos build scripts

on: [ push, pull_request ]

jobs:
  build-main-on-macos:
    name: tvos main
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: [ '11.7', '12.4' ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: set up xcode
        run: echo "export DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer" > ~/.xcode.for.ffmpeg.kit.sh
      - name: run the build script
        run: ./tvos.sh -d -x --disable-arm64
      - name: print success logs
        if: ${{ success() }}
        run: cat build.log
      - name: print failure logs
        if: ${{ failure() }}
        run: |
          tail -50 build.log
          tail -50 ./src/ffmpeg/ffbuild/config.log
  build-lts-on-macos:
    name: tvos lts
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: [ '10.3', '12.4' ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: set up xcode
        run: echo "export DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer" > ~/.xcode.for.ffmpeg.kit.sh
      - name: run the build script
        run: ./tvos.sh -d -l --disable-arm64
      - name: print success logs
        if: ${{ success() }}
        run: cat build.log
      - name: print failure logs
        if: ${{ failure() }}
        run: |
          tail -50 build.log
          tail -50 ./src/ffmpeg/ffbuild/config.log
